// Generated by CoffeeScript 1.8.0

/*
Copyright (c) 2014 Emanuel Rylke

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

(function() {
  var COLORS, Map, PXSIZE, SIZE, ccounter, computer, ctx, draw, i, intervalId, j, map, ngbrs, nsoliders, nvis, player, shuffle, step, walkToPlayer, _i, _j, _k, _l, _ref, _ref1;

  SIZE = 100;

  PXSIZE = 5;

  COLORS = ['#073642', '#586e75', '#b58900', '#268bd2'];

  Map = (function() {
    function Map(size) {
      this.size = size;
      this.map = new Int8Array(this.size * this.size);
    }

    Map.prototype.get = function(_arg) {
      var p0, p1;
      p0 = _arg[0], p1 = _arg[1];
      return this.map[p0 * this.size + p1];
    };

    Map.prototype.set = function(_arg, v) {
      var p0, p1;
      p0 = _arg[0], p1 = _arg[1];
      return this.map[p0 * this.size + p1] = v;
    };

    return Map;

  })();

  map = new Map(SIZE);

  nsoliders = [];

  nsoliders[2] = 0;

  player = [SIZE * 0.8 | 0, SIZE * 0.8 | 0];

  for (j = _i = 0, _ref = SIZE * 0.1 | 0; 0 <= _ref ? _i < _ref : _i > _ref; j = 0 <= _ref ? ++_i : --_i) {
    for (i = _j = 0; 0 <= SIZE ? _j < SIZE : _j > SIZE; i = 0 <= SIZE ? ++_j : --_j) {
      map.set([i, j], 2);
      nsoliders[2]++;
    }
  }

  nsoliders[3] = 0;

  computer = [SIZE * 0.2 | 0, SIZE * 0.2 | 0];

  for (j = _k = _ref1 = SIZE * 0.9 | 0; _ref1 <= SIZE ? _k < SIZE : _k > SIZE; j = _ref1 <= SIZE ? ++_k : --_k) {
    for (i = _l = 0; 0 <= SIZE ? _l < SIZE : _l > SIZE; i = 0 <= SIZE ? ++_l : --_l) {
      map.set([i, j], 3);
      nsoliders[3]++;
    }
  }

  shuffle = function(xs) {
    var r, tmp, _m, _ref2;
    for (i = _m = 0, _ref2 = xs.length; 0 <= _ref2 ? _m < _ref2 : _m > _ref2; i = 0 <= _ref2 ? ++_m : --_m) {
      tmp = xs[i];
      r = Math.random() * xs.length | 0;
      xs[i] = xs[r];
      xs[r] = tmp;
    }
    return null;
  };

  ngbrs = function(_arg, visited, fromSolid) {
    var p, p0, p1, res, _len, _m, _ref2, _ref3, _ref4;
    p0 = _arg[0], p1 = _arg[1];
    res = [];
    _ref2 = [[p0 - 1, p1], [p0 + 1, p1], [p0, p1 - 1], [p0, p1 + 1]];
    for (_m = 0, _len = _ref2.length; _m < _len; _m++) {
      p = _ref2[_m];
      if ((0 <= (_ref3 = p[0]) && _ref3 < SIZE) && (0 <= (_ref4 = p[1]) && _ref4 < SIZE) && !visited.get(p)) {
        if (fromSolid || !(map.get(p) === 1)) {
          res.push(p);
        }
      }
    }
    shuffle(res);
    return res;
  };

  nvis = 0;

  walkToPlayer = function(pp, pn) {
    var fixed, frontier, movedSoliders, newfrontier, p, pb, pbar, pc, pfoo, visited, _len, _len1, _len2, _m, _n, _o, _ref2, _ref3;
    frontier = [pp];
    movedSoliders = 0;
    fixed = new Map(SIZE);
    visited = new Map(SIZE);
    visited.set(pp, 1);
    while (movedSoliders < nsoliders[pn] && frontier.length > 0) {
      newfrontier = [];
      for (_m = 0, _len = frontier.length; _m < _len; _m++) {
        p = frontier[_m];
        fixed.set(p, 1);
        _ref2 = ngbrs(p, visited, map.get(p) === 1);
        for (_n = 0, _len1 = _ref2.length; _n < _len1; _n++) {
          pb = _ref2[_n];
          newfrontier.push(pb);
          visited.set(pb, 1);
          nvis++;
        }
        _ref3 = ngbrs(p, fixed, false);
        for (_o = 0, _len2 = _ref3.length; _o < _len2; _o++) {
          pb = _ref3[_o];
          pfoo = map.get(p);
          pbar = map.get(pb);
          if (pfoo === 2 && pbar === 0) {
            computer = p;
          }
          if (pbar === pn) {
            if (pfoo > 1 && !(pfoo === pn) && Math.random() > 0.9) {
              map.set(p, pn);
              nsoliders[pfoo]--;
              nsoliders[pn]++;
            } else if (pfoo === 0 && Math.random() > 0.2) {
              map.set(p, pn);
              map.set(pb, 0);
            } else {
              pc = ngbrs(pb, fixed, false)[0];
              if (pc && map.get(pc) === 0) {
                map.set(pc, pn);
                map.set(pb, 0);
              }
            }
          }
        }
        if (map.get(p) === pn) {
          movedSoliders++;
        }
      }
      frontier = newfrontier;
    }
    return null;
  };

  ctx = null;

  draw = function() {
    var foo, p0, p1, total, _m, _n;
    ctx.fillStyle = COLORS[0];
    ctx.fillRect(0, 0, (SIZE + 4) * PXSIZE, SIZE * PXSIZE);
    for (p0 = _m = 0; 0 <= SIZE ? _m < SIZE : _m > SIZE; p0 = 0 <= SIZE ? ++_m : --_m) {
      for (p1 = _n = 0; 0 <= SIZE ? _n < SIZE : _n > SIZE; p1 = 0 <= SIZE ? ++_n : --_n) {
        foo = map.get([p1, p0]);
        if (foo) {
          ctx.fillStyle = COLORS[foo];
          ctx.fillRect(p0 * PXSIZE, p1 * PXSIZE, PXSIZE, PXSIZE);
        }
      }
    }
    total = nsoliders[2] + nsoliders[3];
    ctx.fillStyle = COLORS[2];
    ctx.fillRect(SIZE * PXSIZE, 0, PXSIZE * 2, ((nsoliders[2] / total) * SIZE | 0) * PXSIZE);
    ctx.fillStyle = COLORS[3];
    ctx.fillRect((SIZE + 2) * PXSIZE, 0, PXSIZE * 2, ((nsoliders[3] / total) * SIZE | 0) * PXSIZE);
    return null;
  };

  ccounter = 0;

  step = function() {
    nvis = 0;
    ccounter += 0.01;
    computer = [SIZE / 2 + Math.sin(ccounter) * SIZE * 0.45 | 0, SIZE / 2 + Math.cos(ccounter) * SIZE * 0.45 | 0];
    walkToPlayer(player, 2);
    walkToPlayer(computer, 3);
    draw();
    if (nsoliders[2] === 0) {
      alert("The computer won :(");
      clearInterval(intervalId);
    }
    if (nsoliders[3] === 0) {
      alert("You won!");
      return clearInterval(intervalId);
    }
  };

  intervalId = null;

  $(function() {
    var bla, cnvs;
    cnvs = $('canvas');
    ctx = cnvs[0].getContext('2d');
    $(document).mousemove(function(evt) {
      return player = [Math.max(0, Math.min(SIZE - 1, (evt.pageY - cnvs.offset().top) / PXSIZE | 0)), Math.max(0, Math.min(SIZE - 1, (evt.pageX - cnvs.offset().left) / PXSIZE | 0))];
    });
    bla = $('<img src="lwmap.png">');
    return bla.load(function() {
      var blactx, d, _m, _ref2;
      blactx = ($('<canvas height="100" width="100">'))[0].getContext('2d');
      blactx.drawImage(bla[0], 0, 0);
      d = (blactx.getImageData(0, 0, 100, 100)).data;
      for (i = _m = 0, _ref2 = 100 * 100; 0 <= _ref2 ? _m < _ref2 : _m > _ref2; i = 0 <= _ref2 ? ++_m : --_m) {
        if (d[i * 4] < 128) {
          if (map.map[i] > 1) {
            nsoliders[map.map[i]]--;
          }
          map.map[i] = 1;
        }
      }
      return intervalId = setInterval(step, 40);
    });
  });

}).call(this);
